{% set name = 'd2to1' %}
{% set version = '0.2.12' %}
{% set number = '0' %}

about:
    home: https://github.com/embray/{{name}}
    license: GPL
    summary: |
        Allows using distutils2-like setup.cfg files for a package's metadata
        with a distribute/setuptools setup.py

build:
    number: {{number}}

package:
    name: {{name}}
    version: {{version}}

requirements:
    build:
    - setuptools
    - python x.x
    run:
    - setuptools
    - python x.x

source:
    git_tag: {{version}}
    git_url: https://github.com/embray/{{name}}.git
