about:
    home: https://github.com/spacetelescope/pydrizzle
    license: BSD
    summary: Geometrically correct and combine images using Drizzle
build:
    number: '0'
package:
    name: pydrizzle
    version: 6.4.4
requirements:
    build:
    - d2to1
    - astropy >=1.1
    - setuptools
    - stsci.distutils
    - stsci.tools
    - numpy
    - python x.x
    run:
    - astropy >=1.1
    - stsci.tools
    - wxpython [py27]
    - numpy
    - python x.x
source:
    git_tag: 6.4.4
    git_url: https://github.com/spacetelescope/pydrizzle
test:
    imports:
    - pydrizzle
