{% set name = 'gwcs' %}
{% set version = '0.6rc1' %}
{% set tag = 'v' + version %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Generalized World Coordinate System

build:
    number: {{ number }}

package:
<<<<<<< HEAD
    name: {{ name }}
    version: {{ version }}

=======
    name: gwcs
    version: 0.7
>>>>>>> a96a1285ba6cc7b077ba62e2a73d4592dd78003f
requirements:
    build:
    - asdf
    - astropy >=1.1
    - setuptools
    - numpy
    - python x.x
    run:
    - asdf
    - astropy >=1.1
    - numpy
    - python x.x

source:
<<<<<<< HEAD
    git_tag: {{ tag }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

=======
    git_tag: 0.7
    git_url: https://github.com/spacetelescope/gwcs
>>>>>>> a96a1285ba6cc7b077ba62e2a73d4592dd78003f
test:
    imports:
    - gwcs
