{% set name = 'specviz' %}
{% set version = '0.1.2rc3' %}
{% set tag = 'v0.1.2rc3' %}
{% set number = '0' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_tag: {{ tag }}
  git_url: https://github.com/spacetelescope/specviz.git

requirements:
  build:
    - astropy
    - cython
    - jinja2
    - pyyaml
    - pyqtgraph >=0.9.10
    - pyqt
    - scipy
    - yaml
    - setuptools
    - numpy x.x
    - python x.x

  run:
    - astropy
    - cython
    - jinja2
    - pyyaml
    - pyqtgraph >=0.9.10
    - pyqt
    - scipy
    - yaml
    - numpy x.x
    - python x.x

test:
  requires:
    - astropy
  imports:
    - specviz

about:
  home: https://github.com/spacetelescope/specviz
  license: BSD
