about:
    home: http://www.pyqtgraph.org/
    license: MIT
    summary: A pure-Python graphics library for PyQt/PySide (git master build)

build:
    number: '0'

package:
    name: pyqtgraph
    version: 0.9.11

requirements:
    build:
    - setuptools
    - numpy x.x
    - python x.x
    run:
    - pyqt
    - pyopengl
    - numpy x.x
    - python x.x

source:
    git_rev: 670d63cd
    git_url: https://github.com/pyqtgraph/pyqtgraph.git

test:
  requires:
    - pyqt
    - numpy
  imports:
    - pyqtgraph

