{% set name = 'glue-vispy-viewers' %}
{% set version = "0.8" %}
{% set number = '0' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/glue-vispy-viewers/{{ name }}-{{ version }}.tar.gz
  md5: 86134446dc50b5060f0ae8563e0fe677

build:
  number: {{ number }}
  script: python setup.py install --single-version-externally-managed --record record.txt
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pyopengl
    - glue-core >=0.11

  run:
    - python
    - numpy
    - pyopengl
    - glue-core >=0.11
    - matplotlib
    - qtpy
    - pyqt

test:
  imports:
    - glue_vispy_viewers
    - glue_vispy_viewers.scatter
    - glue_vispy_viewers.volume

about:
  home: https://github.com/glue-viz/glue-vispy-viewers
  license: BSD 3-Clause
  summary: 3D viewers for Glue
