{% set name = 'sphere' %}
{% set version = '1.0.6' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/sphere
    license: BSD
    summary: For handling spherical polygons that represent arbitrary regions of the sky 
build:
    number: {{ number }}
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - astropy >=1.1
    - matplotlib
    - setuptools
    - numpy x.x
    - python x.x
    run:
    - astropy >=1.1
    - matplotlib
    - numpy x.x
    - python x.x
source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/sphere
test:
    imports:
    - spherical_geometry
