# NOTE: this is a meta-package that includes the core glue code as well as stable
# plugins. This is the main conda package we want in the Navigator, so we add the
# app: entry here and not in the glue-core package.

{% set name = 'glueviz' %}
{% set version = '0.10.1' %}
{% set number = '0' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: abcb117e102ae9cb00c5dd1bd784c5f3

build:
  number: {{ number }}

requirements:

  build:
    - python
    - setuptools

  run:
    - glue-core >=0.10.1
    - glue-vispy-viewers >=0.7.2

test:
  imports:
    - glue
    - glue.core
    - glue.app.qt
  commands:
    - glue --version
    - glue-deps list

app:
  entry: glue
  icon: logo.png
  summary: Multi-dimensional linked data exploration
  type: desk

about:
  home: http://glueviz.org
  license: BSD 3-Clause
  #license_file: LICENSE
  summary: Multi-dimensional linked data exploration
