# NOTE: this is a meta-package that includes the core glue code as well as stable
# plugins. This is the main conda package we want in the Navigator, so we add the
# app: entry here and not in the glue-core package.

{% set name = 'glueviz' %}
{% set version = '0.11.1' %}
{% set number = '1' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3d5c3ea90d78d3186ff60ff8094e3c0b09c6e040d94210d29a8370a60aa134d5

build:
  number: {{ number }}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  run:
    - glue-core >=0.11.1
    - glue-vispy-viewers >=0.8
    - glue-ginga

app:
  entry: glue
  icon: logo.png
  summary: Multi-dimensional linked data exploration
  type: desk

about:
  home: http://glueviz.org
  license: BSD 3-Clause
  summary: Multi-dimensional linked data exploration
