# NOTE: this is a meta-package that includes the core glue code as well as stable
# plugins. This is the main conda package we want in the Navigator, so we add the
# app: entry here and not in the glue-core package.

{% set name = 'glueviz' %}
{% set version = '0.11.0' %}
{% set number = '0' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: 03954cd633bd7be25472d529034cb8fb

build:
  number: {{ number }}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - glue-core >=0.11.0
    - glue-vispy-viewers >=0.8
    - glue-ginga

  run:
    - glue-core >=0.11.0
    - glue-vispy-viewers >=0.8
    - glue-ginga

app:
  entry: glue
  icon: logo.png
  summary: Multi-dimensional linked data exploration
  type: desk

about:
  home: http://glueviz.org
  license: BSD 3-Clause
  summary: Multi-dimensional linked data exploration
