about:
    home: https://github.com/spacetelescope/astrolib.coords.git
    license: BSD
    summary: astrolib.coords
package:
    name: astrolib.coords
    version: 0.39.6
build:
    number: '0'
requirements:
    build:
    - d2to1
    - stsci.distutils
    - setuptools
    - numpy
    - python x.x
    run:
    - numpy
    - python x.x
source:
    git_tag: 0.39.6
    git_url: https://github.com/spacetelescope/astrolib.coords.git/
test:
    imports:
    - astrolib.coords
