{% set name = 'gcc' %}
{% set version = '4.6.4' %}
{% set number = '0' %}

about:
    home: http://www.netgull.com/gcc/releases/{{name}}-{{version}}
    summary: Gnu Compiler Collection

build:
    number: {{number}}

package:
    name: {{name}}
    version: {{version}}

requirements:
    build:
    - gmp >=4.3.2
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - ppl >=0.11,<1
    run:
    - gmp >=4.2
    - mpfr >=2.3.1
    - mpc >=0.8.1
    - ppl >=0.11,<1

source:
    fn: {{name}}-{{version}}.tar.gz
    url: http://www.netgull.com/gcc/releases/{{name}}-{{version}}/{{name}}-{{version}}.tar.gz
