{% set name = 'relic' %}
{% set version = '1.0.5' %}
{% set number = '0' %}

about:
    home: http://github.com/jhunkeler/relic
    license: BSD
    summary: Release I Control, for git
build:
    number: {{ number }}
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - setuptools
    - python x.x
    run:
    - python x.x
source:
    git_tag: {{ version }}
    git_url: https://github.com/jhunkeler/relic.git
test:
    imports:
    - relic
    - relic.release
    - relic.git
