{% set name = 'stsci.distutils' %}
{% set version = '0.3.8' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/stsci.distutils
    license: BSD
    summary: |
        distutils/packaging-related utilities used by some of STScI's packages

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - setuptools
    - numpy
    - python x.x
    run:
    - nose
    - numpy
    - python x.x

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - stsci.distutils
