about:
    home: http://www.stsci.edu/hst/observatory/crds/
    license: AURA
    summary: crds
build:
    number: '0'
    preserve_egg_dir: 'no'
package:
    name: crds
    version: 6.0.0
requirements:
    build:
    - d2to1
    - astropy >=1.1
    - numpy x.x
    - setuptools
    - python x.x
    run:
    - astropy >=1.1
    - numpy x.x
    - python x.x
source:
    git_tag: 6.0.0
    git_url: https://github.com/spacetelescope/crds
test:
    imports:
    - crds
