about:
    home: https://github.com/spacetelescope/pysynphot
    license: BSD
    summary: pysynphot
build:
    number: '0'
    preserve_egg_dir: 'yes'
package:
    name: pysynphot
    version: 0.9.8.3
requirements:
    build:
    - d2to1
    - nose
    - stsci.distutils
    - astropy >=1.2
    - cython
    - numpy x.x
    - matplotlib
    - setuptools
    - python x.x
    run:
    - nose
    - astropy >=1.2
    - cython
    - numpy x.x
    - matplotlib
    - python x.x
source:
    git_url: https://github.com/spacetelescope/pysynphot
test:
    imports:
    - pysynphot
