about:
    home: https://github.com/spacetelescope/stsci.tools
    license: GPL
    summary: stsci.tools
build:
    number: '0'
    preserve_egg_dir: 'yes'
package:
    name: stsci.tools
    version: 3.4.2.1
requirements:
    build:
    - d2to1
    - astropy >=1.1
    - pytools
    - setuptools
    - stsci.distutils
    - numpy
    - python x.x
    run:
    - astropy >=1.1
    - numpy
    - pytools
    - stsci.distutils
    - python x.x
source:
    git_url: https://github.com/spacetelescope/stsci.tools
test:
    imports:
    - stsci.tools
