{% set name = 'acstools' %}
{% set version = '2.0.2' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: For analyzing ACS data
build:
    number: {{ number }}
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - d2to1
    - stsci.distutils
    - python x.x
    - astropy >=1.1
    - numpy x.x
    - scipy
    - scikit-image
    - matplotlib
    - stsci.imagestats
    - stsci.tools
    - setuptools
    run:
    - astropy >=1.1
    - numpy x.x
    - scipy
    - scikit-image
    - matplotlib
    - stsci.imagestats
    - stsci.tools
    - setuptools
    - python x.x
source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git
test:
    commands:
    - acs_destripe --help
    - acs_destripe_plus --help
    imports:
    - acstools
