{% set name = 'pyds9' %}
{% set version = '1.9.0.dev' %}
{% set number = '1' %}

about:
    home: https://github.com/ericmandel/{{ name }}
    license: BSD
    summary: |
        (Supervised master build)
        Python connection to SAOimage DS9 via XPA

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy
    - cython
    - ds9
    - six
    - setuptools
    - numpy
    - python x.x
    run:
    - astropy
    - ds9
    - six
    - numpy
    - python x.x

source:
    git_rev: 3761d7ac151f8c8729d0fb6cdba017cadf278283
    git_url: https://github.com/ericmandel/{{ name }}.git

test:
    imports:
    - pyds9
