{% set name = 'pyds9' %}
{% set version = "1.9.0.dev" ~ GIT_DESCRIBE_NUMBER ~ "+" ~ GIT_DESCRIBE_HASH %}
{% set number = '2' %}

about:
    home: https://github.com/ericmandel/{{ name }}
    license: BSD
    summary: |
        (Supervised master build)
        Python connection to SAOimage DS9 via XPA

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy
    - cython
    - ds9
    - six
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - astropy
    - ds9
    - six
    - numpy
    - python

source:
    git_rev: c1bf67ab195bd7eb0c662755c2df35df014482b0
    git_url: https://github.com/ericmandel/{{ name }}.git

test:
    imports:
    - pyds9
